name: Label documentation only PRs.
author: Jakub Kuczys
description: >-
  GitHub action for labelling and unlabelling PRs based on whether they contain
  only documentation changes. Supports file patterns and Python docstrings.
runs:
  using: composite
  steps:
    - name: Checkout the base branch for the pull request.
      uses: actions/checkout@v3

    - name: Checkout the merge branch for the pull request.
      run: |-
        git fetch origin +refs/pull/${{ github.event.pull_request.number }}/merge
        git checkout FETCH_HEAD
      shell: bash

    - name: Setup Python for the action.
      id: python-for-action
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        update-environment: false

    - name: Run the action.
      run: >-
        pipx run
        --python '${{ steps.python-for-action.outputs.python-path }}'
        --spec '${{ github.action_path }}'
        label_doconly_changes
      shell: bash
