name: Label documentation only PRs.
author: Jakub Kuczys
description: >-
  Label PRs based on whether they contain only documentation changes.
  Supports file patterns and Python docstrings.
branding:
  color: green
  icon: book
runs:
  using: composite
  steps:
    - name: Checkout the base branch for the pull request.
      uses: actions/checkout@v6

    - name: Checkout the merge branch
      env:
        REF_TO_FETCH: |-
          ${{
            github.event.pull_request.state == 'open'
              && format('+refs/pull/{0}/merge', github.event.pull_request.number)
              || github.event.pull_request.merge_commit_sha
          }}
      run: |-
        git fetch origin "$REF_TO_FETCH"
        git checkout -f FETCH_HEAD
      shell: bash

    - name: Fetch the base ref
      env:
        LDC_BASE_REF: |-
          ${{
            github.event.pull_request.merged
              && github.event.pull_request.base.sha
              || github.base_ref
          }}
      run: |-
        git fetch origin "$LDC_BASE_REF"
        echo "LDC_BASE_REF=$(git rev-parse FETCH_HEAD)" >> "$GITHUB_ENV"
      shell: bash

    - name: Setup Python for the action.
      id: python-for-action
      uses: actions/setup-python@v6
      with:
        python-version: "3.11"
        update-environment: false

    - name: Run the action.
      env:
        PATH_TO_PYTHON: ${{ steps.python-for-action.outputs.python-path }}
        GITHUB_TOKEN: ${{ github.token }}
      run: >-
        pipx run --python "$PATH_TO_PYTHON" --spec "$GITHUB_ACTION_PATH" label-doconly-changes
      shell: bash
