name: Label documentation only PRs.
author: Jakub Kuczys
description: >-
  Label PRs based on whether they contain only documentation changes.
  Supports file patterns and Python docstrings.
branding:
  color: green
  icon: book
runs:
  using: composite
  steps:
    - name: Checkout the base branch for the pull request.
      uses: actions/checkout@v3

    - name: Checkout the merge branch for the open pull request.
      if: github.event.pull_request.state == 'open'
      run: |-
        git fetch origin +refs/pull/${{ github.event.pull_request.number }}/merge
        git checkout -f FETCH_HEAD
      shell: bash

    - name: Checkout the merge branch for the closed pull request.
      if: github.event.pull_request.state != 'open'
      run: |-
        git fetch origin ${{ github.event.pull_request.merge_commit_sha }}
        git checkout -f FETCH_HEAD
      shell: bash

    - name: Setup Python for the action.
      id: python-for-action
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        update-environment: false

    - name: Run the action.
      run: >-
        pipx run
        --python '${{ steps.python-for-action.outputs.python-path }}'
        --spec '${{ github.action_path }}'
        label-doconly-changes
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        LDC_BASE_REF: |-
          ${{
            github.event.pull_request.merged
              && github.event.pull_request.base.sha
              || github.base_ref
          }}
        LDC_HEAD_REF: |-
          ${{
            github.event.pull_request.merged
              && github.event.pull_request.head.sha
              || ''
          }}
