name: Tests

on: [push, pull_request]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository.
        uses: actions/checkout@v3

      - name: Setup Python.
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install the project.
        run: pip install .[test]

      - name: Run pytest.
        run: pytest
